account/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from account.views import profile

from registration.backends.default.views import ActivationView
from registration.backends.default.views import RegistrationView

urlpatterns = patterns('',
                       url(r'^profil/(?P<user_id>\d+)/',
                           profile,
                           name='profile'),
                       url(r'^profil/',
                           profile,
                           name='my_profile'),

                       # Registration
                       url(r'^aktivasyon/tamamlandi/$',
                           TemplateView.as_view(template_name='registration/activation_complete.html'),
                           name='registration_activation_complete'),
                       # Activation keys get matched by \w+ instead of the more specific
                       # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                       # that way it can return a sensible "invalid key" message instead of a
                       # confusing 404.
                       url(r'^aktivasyon/(?P<activation_key>\w+)/$',
                           ActivationView.as_view(),
                           name='registration_activate'),
                       url(r'^kayit/$',
                           RegistrationView.as_view(),
                           name='registration_register'),
                       url(r'^kayit/tamamlandi/$',
                           TemplateView.as_view(template_name='registration/registration_complete.html'),
                           name='registration_complete'),
                       url(r'^kayit/kapandi/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),

                       # Authentication
                       url(r'^giris/$',
                           auth_views.login,
                           {'template_name': 'account/login.html'},
                           name='login'),
                       url(r'^cikis/$',
                           auth_views.logout,
                           {'template_name': 'account/logout.html'},
                           name='logout'),

                       # Password Change
                       url(r'^sifre/degistir/$',
                           auth_views.password_change,
                           name='auth_password_change'),
                       url(r'^sifre/degistir/tamam/$',
                           auth_views.password_change_done,
                           name='auth_password_change_done'),

                       # Password Reset
                       url(r'^sifre/yenile/$',
                           auth_views.password_reset,
                           name='auth_password_reset'),
                       url(r'^sifre/yenile/onayla/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
                           auth_views.password_reset_confirm,
                           name='auth_password_reset_confirm'),
                       url(r'^sifre/yenile/tamamlandi/$',
                           auth_views.password_reset_complete,
                           name='auth_password_reset_complete'),
                       url(r'^sifre/yenile/tamam/$',
                           auth_views.password_reset_done,
                           name='auth_password_reset_done'),
                       )

teamsbook/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', 'feed.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hesap/', include('account.urls')),
    url(r'^yorumlar/', include('django.contrib.comments.urls')),
    url(r'^mesajlar/', include('communication.urls')),
)

urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
    'document_root': settings.MEDIA_ROOT}))

feed/models.py
#-*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext as _

from account.models import CustomUser
from community.models import Group
# from utilities.models import Image


class Post(models.Model):
    url = models.URLField(
        _(u'Link'),
        blank=True,
        null=True)
    message = models.CharField(
        _(u'Mesaj'),
        max_length=140,
        blank=True,
        null=True)
    """
    image = models.OneToOneField(
        Image,
        verbose_name=_(u'Fotoğraf'),
        blank=True,
        null=True)
    """
    image = models.ImageField(
        _(u'Fotoğraf'),
        upload_to='photos/',
        null=True,
        blank=True)
    # video - not now of course
    date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_(u'Gönderi zamanı'))
    # comments ??

    class Meta:
        verbose_name = _(u'gönderi')
        verbose_name_plural = _(u'gönderiler')


class UserPost(Post):
    owner = models.ForeignKey(CustomUser, related_name='posts')


class GroupPost(Post):
    writer = models.ForeignKey(CustomUser)

    owner = models.ForeignKey(Group, related_name='posts')

feed/forms.py
from django import forms
from django.utils.translation import ugettext as _

from feed.models import UserPost


class PostForm(forms.ModelForm):
    message = forms.CharField(label=_(u'Mesaj'), widget=forms.Textarea)
    class Meta:
        model = UserPost
        fields = ('message', 'image', 'url')


class TextFeedForm(forms.ModelForm):
    message = forms.CharField(label=_(u'Mesaj'), widget=forms.Textarea)
    class Meta:
        model = UserPost
        fields = ('message',)

class PhotoFeedForm(forms.ModelForm):
    message = forms.CharField(label=_(u'Mesaj'), widget=forms.Textarea)
    class Meta:
        model = UserPost
        fields = ('message', 'image')

class LinkFeedForm(forms.ModelForm):
    message = forms.CharField(label=_(u'Mesaj'), widget=forms.Textarea)
    class Meta:
        model = UserPost
        fields = ('message', 'url')

feed/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from feed.forms import PostForm, TextFeedForm, PhotoFeedForm, LinkFeedForm
from feed.models import UserPost


@login_required
def home(request):
    profile = request.user
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.owner = request.user
            post.save()
            profile_feeds = UserPost.objects.filter(owner=profile).order_by('-date')
            message_form = TextFeedForm()
            photo_message_form = PhotoFeedForm()
            link_message_form = LinkFeedForm()
            return render(request, 'feed/home.html', {'profile': profile,
                                                            'profile_feeds': profile_feeds,
                                                            'message_form': message_form,
                                                            'photo_message_form': photo_message_form,
                                                            'link_message_form': link_message_form})
        else:
            profile_feeds = UserPost.objects.filter(owner=profile).order_by('-date')
            message_form = TextFeedForm(request.POST)
            photo_message_form = PhotoFeedForm(request.POST, request.FILES)
            link_message_form = LinkFeedForm(request.POST)
            return render(request, 'feed/home.html', {'profile': profile,
                                                            'profile_feeds': profile_feeds,
                                                            'message_form': message_form,
                                                            'photo_message_form': photo_message_form,
                                                            'link_message_form': link_message_form})
    else:
        profile_feeds = UserPost.objects.filter(owner=profile).order_by('-date')
        message_form = TextFeedForm()
        photo_message_form = PhotoFeedForm()
        link_message_form = LinkFeedForm()
        return render(request, 'feed/home.html', {'profile': profile,
                                                        'profile_feeds': profile_feeds,
                                                        'message_form': message_form,
                                                        'photo_message_form': photo_message_form,
                                                        'link_message_form': link_message_form})

templates/feed/home.html
{% extends "base.html" %}


{% block title %}Arkadaşlar{% endblock %}

{% block content %}
          <div class="tabbable tabs-left">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#text" data-toggle="tab"><i class="icon-pencil icon-white"></i> Yazı</a></li>
              <li><a href="#photo" data-toggle="tab"><i class="icon-picture icon-white"></i> Fotoğraf</a></li>
              <li><a href="#link" data-toggle="tab"><i class="icon-signal icon-white"></i> Link</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="text">
                  <form class="well" method="POST" action=".">
                    {% csrf_token %}
                    <p><label for="id_message">Mesaj:</label> <textarea class="input-xxlarge" cols="30" id="id_message" name="message" rows="10"></textarea></p>
                    <button class="btn btn-primary" type="submit">Gönder</button>
                  </form>
                </div>
                <div class="tab-pane" id="photo">
                  <form class="well" method="POST" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <p><label for="id_message">Mesaj:</label> <textarea class="input-xxlarge" cols="30" id="id_message" name="message" rows="10"></textarea></p>
                    <p><label for="id_image">Fotoğraf:</label>
                    {{ photo_message_form.image }}</p>
                    <button class="btn btn-primary" type="submit">Gönder</button>
                  </form>
                </div>
                <div class="tab-pane" id="link">
                  <form class="well" method="POST" action=".">
                    {% csrf_token %}
                    <p><label for="id_message">Mesaj:</label> <textarea class="input-xxlarge" cols="30" id="id_message" name="message" rows="10"></textarea></p>
                    <p><label for="id_url">Link:</label>
                    {{ link_message_form.url }}</p>
                    <button class="btn btn-primary" type="submit">Gönder</button>
                  </form>
                </div>
            </div>
          </div>
        {% for feed in profile_feeds %}
          {% if feed.image %}
              <div class="row-fluid">
                <ul class="thumbnails well">
                  <li class="span3">
                    <a class="thumbnail">
                      <img src="{{ feed.image.url }}" alt="">
                    </a>
                  </li>
                  <li class="span3">
                    <p>{{ feed.message }}</p>
                  </li>
                </ul>
              </div>
          {% elif feed.url %}
              <p class="well">{{ feed.message }}<br /><a href="{{ feed.url }}">Linke git &raquo;</a></p>
          {% else %}
              <p class="well">{{ feed.message }}</p>
          {% endif %}
        {% endfor %}
{% endblock %}